spring.application.name=flights-api

spring.datasource.url=jdbc:postgresql://localhost:5433/demo?currentSchema=bookings,public
spring.datasource.username=postgres
spring.datasource.password=password

# JPA Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Jackson Configuration
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
spring.jackson.time-zone=UTC
